# Configuração padrão para o ambiente de desenvolvimento (SQLite)
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# Configuração para o ambiente de produção (Render + PostgreSQL)
# O Rails 8 usará estas configurações quando detectar que está no ar.
production:
  adapter: postgresql
  encoding: unicode
  # O Render preenche a URL do banco automaticamente se você conectar o Database ao Web Service
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>