# Configuração padrão para o ambiente de desenvolvimento (SQLite)
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# Configuração para o ambiente de produção (Render + PostgreSQL)
# O Rails 8 usará estas configurações quando detectar que está no ar.
production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
  cable:
    <<: *primary_production